env:
  browser: true
  jest: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:jsx-a11y/recommended"
  - "prettier"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
settings:
  react:
    version: "16.13"
plugins:
  - "react"
  - "react-hooks"
  - "@typescript-eslint"
  - "jsx-a11y"
rules:
  no-console:
    - error
    - allow:
        - error
        - warn
overrides:
  - files: "*.tsx"
    rules:
      "@typescript-eslint/explicit-function-return-type": 0
